from telegram import ReplyKeyboardMarkup,InlineKeyboardButton,InlineKeyboardMarkup
from telegram.ext import Updater, CommandHandler,ConversationHandler,MessageHandler,Filters,CallbackQueryHandler
key=ReplyKeyboardMarkup([['⬅Restart']],resize_keyboard=True)
dic={'Afghanistan':'Kabul',
'Albania':'Tirana (Tirane)',
'America':'Vashington',
'Algeria':'Algiers',
'Andorra':'Andorra la Vella',
'Angola':'Luanda',
'Antigua':'Barbuda Saint Johns',
'Argentina':'Buenos Aires',
'Armenia':'Yerevan',
'Australia':'Canberra',
'Austria':'Vienna',
'Azerbaijan':'Baku',
'Bahamas':'assau',
'Bahrain':'anama',
'Bangladesh':'Dhaka',
'Barbados':'Bridgetown',
'Belarus':'Minsk',
'Belgium':'Brussels',
'Belize':'Belmopan',
'Benin':'Porto Novo',
'Bhutan':'Thimphu',
'Bolivia':'La Paz (administrative), Sucre (official)',
'Bosnia and Herzegovina':'Sarajevo',
'Botswana':'Gaborone',
'Brazil':'Brasilia',
'Brunei	Bandar':'Seri Begawan',
'Bulgaria':'Sofia',
'Burkina Faso':'Ouagadougou',
'Burundi':'Gitega',
'Cambodia':'Phnom Penh',
'Cameroon':'Yaounde',
'Canada':'Ottawal',
'Cape Verde':'Praia',
'Central African Republic':'Bangui',
'Chad':'NDjamena',
'Chile':'Santiago',
'China':'Beijing',
'Colombia':'Bogota',
'Comoros':'Moroni',
'Congo, Democratic Republic of the':'Kinshasa',
'Congo, Republic of the':'Brazzaville',
'Costa Rica':'San Jose',
'Côte dIvoire (Ivory Coast)':'Yamoussoukro',
'Croatia':'Zagreb',
'Cuba':'Havana',
'Cyprus':'Nicosia',
'Czech Republic (Czechia)':'Prague',
'Denmark':'Copenhagen',
'Djibouti':'Djibouti',
'Dominica':'Roseau',
'Dominican Republic':'Santo Domingo',
'East Timor':'Dili',
'Ecuador':'Quito',
'Egypt':'Cairo',
'El Salvador':'San Salvador',
'England':'London',
'Equatorial Guinea':'Malabo',
'Eritrea':'Asmara',
'Estonia':'Tallinn',
'Eswatini (Swaziland)':'Mbabana',
'Ethiopia':'Addis Ababa',
'Federated States of Micronesia':'Palikir',
'Fiji':'Suva',
'Finland':'Helsinki',
'France':'Paris',
'Gabon':'Libreville',
'Gambia':'Banjul',
'Georgia':'Tbilisi',
'Germany':'Berlin',
'Ghana':'Accra',
'Greece':'Athens',
'Grenada':'Saint Georges',
'Guatemala':'Guatemala City',
'Guinea':'Conakry',
'Guinea-Bissau':'Bissau',
'Guyana':'Georgetown',
'Haiti':'Port au Prince',
'Honduras':'Tegucigalpa',
'Hungary':'Budapest',
'Iceland':'Reykjavik',
'India':'New Delhi',
'Indonesia':'Jakarta',
'Iran':'Tehran',
'Iraq':'Baghdad',
'Ireland':'Dublin',
'Israel':'Jerusalem',
'Italy':'Rome',
'Jamaica':'Kingston',
'Japan':'Tokyo',
'Jordan':'Amman',
'Kazakhstan':'Nur-Sultan',
'Kenya':'Nairobi',
'Kiribati':'Tarawa Atoll',
'Kosovo':'Pristina',
'Kuwait':'Kuwait City',
'Kyrgyzstan':'Bishkek',
'Laos':'Vientiane',
'Latvia':'Riga',
'Lebanon':'Beirut',
'Lesotho':'Maseru',
'Liberia':'Monrovia',
'Libya':'Tripoli',
'Liechtenstein':'Vaduz',
'Lithuania':'Vilnius',
'Luxembourg':'Luxembourg',
'Madagascar':'Antananarivo',
'Malawi':'Lilongwe',
'Malaysia':'Kuala Lumpur',
'Maldives':'Male',
'Mali':'Bamako',
'Malta':'Valletta',
'Marshall Islands':'Majuro',
'Mauritania':'Nouakchott',
'Mauritius':'Port Louis',
'Mexico':'Mexico City',
'Moldova':'Chisinau',
'Monaco':'Monaco',
'Mongolia':'Ulaanbaatar',
'Montenegro':'Podgorica',
'Morocco':'Rabat',
'Mozambique':'Maputo',
'Myanmar':'Nay Pyi Taw',
'Namibia':'Windhoek',
'Nauru':'No official capital',
'Nepal':'Kathmandu',
'Netherlands':'Amsterdam',
'New Zealand':'Wellington',
'Nicaragua':'Managua',
'Niger':'Niamey',
'Nigeria':'Abuja',
'North Korea':'Pyongyang',
'North Macedonia':'Skopje',
'Northern Ireland':'Belfast',
'Norway':'Oslo',
'Oman':'Muscat',
'Pakistan':'Islamabad',
'Palau':'Melekeok',
'Panama':'Panama City',
'Papua New Guinea':'Port Moresby',
'Paraguay':'Asuncion',
'Peru':'Lima',
'Philippines':'Manila',
'Poland':'Warsaw',
'Portugal':'Lisbon',
'Qatar':'Doha',
'Romania':'Bucharest',
'Russia':'Moscow',
'Rwanda':'Kigali',
'Saint Kitts':'Basseterre',
'Saint Lucia':'Castries',
'Saint Vincent':'Kingstown',
'Samoa':'Apia',
'San Marino':'San Marino',
'Sao Tome':'Sao Tome',
'Saudi Arabia':'Riyadh',
'Scotland':'Edinburgh',
'Senegal':'Dakar',
'Serbia':'Belgrade',
'Seychelles':'Victoria',
'Sierra Leone':'Freetown',
'Singapore':'Singapore',
'Slovakia':'Bratislava',
'Slovenia':'Ljubljana',
'Solomon Islands':'Honiara',
'Somalia':'Mogadishu',
'South Africa':'Pretoria, Bloemfontein, Cape Town',
'South Korea':'Seoul',
'South Sudan':'Juba',
'Spain':'Madrid',
'Sri Lanka':'Lolombo',
'Sudan':'Khartoum',
'Suriname':'Paramaribo',
'Sweden':'Stockholm',
'Switzerland':'Bern',
'Syria':'Damascus',
'Taiwan':'Taipei',
'Tajikistan':'Dushanbe',
'Tanzania':'Dodoma',
'Thailand':'Bangkok',
'Togo':'Lome',
'Tonga':'Nukualofa',
'Trinidad':'Port of Spain',
'Tunisia':'Tunis',
'Turkey':'Ankara',
'Turkmenistan':'Ashgabat',
'Tuvalu':'Funafuti',
'Uganda':'Kampala',
'Ukraine':'Kiev',
'United Arab Emirates':'Abu Dhabi',
'United Kingdom':'London',
'United States':'Washington',
'Uruguay':'Montevideo',
'Uzbekistan':'Tashkent',
'Vanuatu':'Port Vila',
'Vatican City':'Vatican City',
'Venezuela':'Caracas',
'Vietnam':'Hanoi',
'Wales':'Cardiff',
'Yemen':'Sanaa',
'Zambia':'Lusaka',
'Zimbabwe':'Harare',
     }
def language(update,context):
    keys=ReplyKeyboardMarkup([['🇺🇿 O\'zbekcha'],['🇷🇺Русский']],resize_keyboard=True)
    update.message.reply_html('Please choose language:', reply_markup=keys)
    return 'start'
def start(update, context):
    message=update.message.text
    if message=='🇺🇿 O\'zbekcha':
        update.message.reply_text('Assalomu aleykum {}\n{}'.format(update.message.from_user.first_name,'Start buyrug\'ini tanlaganizdan minnatdormiz!\nBu bot orqali siz Davlatlar poytaxtlari haqida bilib olishingiz mumkin.\nBotga Davlat nomini inglizchada kiriting!'),reply_markup=key)
    if message=='🇷🇺Русский':
        update.message.reply_text('Здравствуйте {}\n{}'.format(update.message.from_user.first_name,'Спасибо, что нажали Start!\n\nДобро пожаловать!\nС помощью этого бота вы узнаете о столице Государств!\nВведите название государства в боте латиницей!'),reply_markup=key)

    return 'text'
def text(update,context):
    text=update.message.text.title()
    text1 = update.message.text
    if text1 == '⬅Restart':
        keys = ReplyKeyboardMarkup([['🇺🇿 O\'zbekcha'], ['🇷🇺Русский']], resize_keyboard=True)
        update.message.reply_html('Please choose language:', reply_markup=keys)
        return 'start'
    if text in dic:
        update.message.reply_html('<strong>Capital</strong>:{}'.format(dic[text]))
    else:
        update.message.reply_text('Не найдено...')
def begin():
    updater = Updater('1786474330:AAEB5gd4KjckFrX3YCmV1Za00C-9qrq7hkU',use_context=True)
    dispatcher = updater.dispatcher
    handler=ConversationHandler(
        entry_points=[CommandHandler('start',language)],
        states={
            'start':[MessageHandler(Filters.text,start)
            ],
            'text':[MessageHandler(Filters.text,text)],
            },
        fallbacks = [MessageHandler(Filters.text, start)])
    dispatcher.add_handler(handler)
    updater.start_polling()
begin()